version: '3.8'

services:
  backend:
    build: ./backend
    container_name: mp-backend
    ports:
      - "3000:3000"
    environment:
      - DB_USER=sa
      - DB_PASSWORD=Your_strong@Pass123
      - DB_SERVER=host.docker.internal
      - DB_DATABASE=master
      - DB_PORT=1433
    depends_on:
      - sqlserver

  frontend:
    build: ./frontend
    container_name: mp-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mp-db
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_strong@Pass123"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
